var GeographicLib, L;

L = require('leaflet');

GeographicLib = require("geographiclib");

L.GeographicUtil = L.extend(L.GeographicUtil || {}, {
  geod: GeographicLib.Geodesic.WGS84,
  distance: function(a, b) {
    var r;
    r = this.geod.Inverse(a[0], a[1], b[0], b[1]);
    return r.s12.toFixed(3);
  },
  Polygon: function(points) {
    var i, len, point;
    this.geod = GeographicLib.Geodesic.WGS84;
    this.poly = this.geod.Polygon(false);
    for (i = 0, len = points.length; i < len; i++) {
      point = points[i];
      this.poly.AddPoint(point[0], point[1]);
    }
    this.poly = this.poly.Compute(false, true);
  }
});

L.GeographicUtil.Polygon.prototype = {
  perimeter: function() {
    return this.poly.perimeter;
  },
  area: function() {
    return Math.abs(this.poly.area);
  }
};

// ---
// generated by coffee-script 1.9.2
