var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

L.Cut = (function(superClass) {
  extend(Cut, superClass);

  Cut.TYPE = 'cut';

  function Cut(map, options) {}

  return Cut;

})(L.Handler);

// ---
// generated by coffee-script 1.9.2
